Repository SUSE/doc-modular, pull requests merged in 2022-05, with the labels that each got.

#53 doc-kit update: add missing zypper entity
  doc-kit.conf
  xml/generic-entities.ent
Labels: bug

#52 Getting started with BCIs
  DC-concept-bci-get-started
  xml/concept-bci-get-started.xml
  xml/concept-bci-variants.xml
  xml/concept-bci.xml
Labels: WIP

#54 Use suse2022-ns stylesheets for en-us
  DC-concept-bci
  DC-concept-bci-get-started
  DC-concept-bci-variants
  DC-concept-klp
  DC-concept-manage-virtual-machines-libvirt
  DC-concept-minimal-vm
  DC-concept-sudo
  DC-concept-systemd
  DC-concept-time-synchronization-ntp
  DC-concept-virtual-disk-cache-modes
  DC-concept-virtualization
  DC-concept-zypper
  DC-reference-managing-systemd-targets-systemctl
  DC-reference-network-bonding-teaming-comparison
  DC-reference-systemctl-enable-disable-services
  DC-reference-systemctl-start-stop-services
  DC-reference-zypper-install
  DC-task-add-modules-extensions-after-installation
  DC-task-assign-pci-device-libvirt
  DC-task-check-cpu-temperature
  DC-task-configure-network-bonding
  DC-task-configure-network-teaming
  DC-task-configure-ntp
  DC-task-configure-sudo
  DC-task-configure-virtual-machine-manager
  DC-task-create-systemd-timers
  DC-task-debug-failed-systemd-services
  DC-task-delete-modules-extensions
  DC-task-forward-root-mail
  DC-task-install-virtualization-components
  DC-task-modify-kernel-boot-parameter
  DC-task-register-deregister-product-after-installation
  DC-task-send-termination-signals-systemd
  DC-task-set-up-uefi-http-boot-server
  DC-task-setup-free-radius-server
  DC-task-working-sudo
Labels: enhancement
