Repository SUSE/doc-modular, pull requests merged in 2023-10, with the labels that each got.

#155 Add network bonding and teaming topics
  DC-network-bond-managing-devices
  DC-network-team-managing-devices
  DC-reference-network-bonding-teaming-comparison
  DC-task-configure-network-bonding
  DC-task-configure-network-teaming
  articles/network-bond-managing-devices.asm.xml
  articles/network-team-managing-devices.asm.xml
  references/network-bond-team-comparison.xml
  tasks/network-bond-configure.xml
  tasks/network-bond-enable-hotplug.xml
  tasks/network-bond-team-remove.xml
  tasks/network-team-add-vlans.xml
  tasks/network-team-configure.xml
  xml/reference-network-bonding-teaming-comparison.xml
  xml/task-configure-network-bonding.xml
  xml/task-configure-network-teaming.xml
Labels: cat:Network

#201 Create new article on sudo administration/configuration
  DC-sudo-configure-superuser-privileges
  articles/sudo-configure-superuser-privileges.asm.xml
  concepts/sudo-configuration-intro.xml
  references/sudo-best-practices.xml
  references/sudo-edit-configuration.xml
  references/sudo-user-authorization.xml
  tasks/sudo-change-pw-timeout.xml
  tasks/sudo-creating-custom-configuration.xml
  tasks/sudo-start-shell-as-root.xml
  tasks/sudo-troubleshoot.xml
  tasks/sudo-without-root-password.xml
Labels: documentation, WIP

#176 systemd basics
  DC-systemd-basics
  articles/systemd-basics.asm.xml
  concepts/systemd-as-regular-user.xml
  concepts/systemd-best-practices.xml
  concepts/systemd-logging.xml
  concepts/systemd-targets.xml
  concepts/systemd-unit-dependencies.xml
  concepts/systemd-unit-file.xml
  concepts/types-of-systemd-unit-files.xml
  concepts/what-is-systemd.xml
  references/systemctl-cheatsheet.xml
  references/systemd-gnu-accounting-utilities.xml
  references/systemd-termination-signal-new.xml
  tasks/systemd-create-service.xml
  tasks/systemd-troubleshooting.xml
Labels: cat:SysMgt

#224 Make meta name=category consistent
  articles/alp-dolomite.asm.xml
  articles/sle-minimal-vm.asm.xml
  articles/virt-scenario-creating-customized-vm-guests.asm.xml
Labels: enhancement

#227 Remove DC-task-setup-free-radius-server
  DC-task-setup-free-radius-server
  xml/task-setup-free-radius-server.xml
Labels: duplicate
