Repository SUSE/doc-modular, pull requests merged in 2023-08, with the labels that each got.

#169 Fixes as suggested by Otto
  articles/sudo-run-commands-as-superuser.asm.xml
  concepts/difference-between-sudo-and-su.xml
  concepts/sudo-concept.xml
  references/sudo-best-practices.xml
  references/sudo-commands.xml
  references/sudo-edit-configuration.xml
  references/sudo-troubleshoot.xml
  references/sudo-user-authorization.xml
  tasks/sudo-change-pw-timeout.xml
  tasks/sudo-manage-wheel-group.xml
  tasks/sudo-run-command.xml
  tasks/sudo-start-shell-as-root.xml
  tasks/sudo-without-root-password.xml
Labels: enhancement, cat:SysMgt

#185 Fix DOCTEAM-1056: Remove obsolete sudo articles
  DC-concept-sudo
  DC-task-configure-sudo
  DC-task-working-sudo
Labels: cat:SysMgt

#186 Remove obsolete task-create-systemd-timers
  DC-task-create-systemd-timers
  xml/task-create-systemd-timers.xml
Labels: bug, duplicate

#179 Review of CPU temperature article
  DC-cpu-check-temperature
  articles/CPUTemp.asm.xml
  articles/cpu-check-temperature.asm.xml
  concepts/cpu-check-temperature-intro.xml
  glues/cpu-check-temperature-more-info.xml
  references/cpu-check-temperature-troubleshoot.xml
  tasks/cpu-check-temperature-configure.xml
  tasks/cpu-check-temperature-get-data.xml
  tasks/cpu-check-temperature-realtime.xml
  tasks/cpu-temp-check.xml
Labels: cat:SysMgt
